workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    environment:
      xcode: latest
      node: "20.5.0"            # Node version as string
      npm:
        version: "10.2.0"       # Latest npm version as string
        # authToken: ${{secrets.NPM_TOKEN}}  # Uncomment if you need npm auth
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -scheme App -workspace App.xcworkspace \
            -sdk iphoneos -configuration Release archive \
            -archivePath $CM_BUILD_DIR/ios_archive/App.xcarchive
    artifacts:
      - $CM_BUILD_DIR/ios_archive/**/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com