workflows:
  ios-capacitor:
    name: iOS Capacitor Build
    environment:
      xcode: latest
      node: 18
      npm: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -scheme App -workspace App.xcworkspace \
            -sdk iphoneos -configuration Release archive \
            -archivePath $CM_BUILD_DIR/ios_archive/App.xcarchive
    artifacts:
      - $CM_BUILD_DIR/ios_archive/**/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com